name: juicer
options:
  bundleIdPrefix: com.even.juicer
packages:
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    from: 2.6.0
targets:
  juicer:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: juicer/sources
      - path: juicer/sources/resources/AppIcon.icns
    dependencies:
      - package: Sparkle
        codeSignOnCopy: true
    settings:
      CODE_SIGN_ENTITLEMENTS: juicer/sources/resources/juicer.entitlements
      INFOPLIST_FILE: juicer/sources/resources/info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.even.juicer
      PRODUCT_NAME: Juicer
      MACOSX_DEPLOYMENT_TARGET: "14.0"
      ENABLE_HARDENED_RUNTIME: YES

