import Foundation

struct PrunableCacheItem: Identifiable, Hashable {
    let id: UUID = UUID()
    let name: String
    let path: String
    let description: String
    var size: Int64
    var isSelected: Bool
}

class CachePrunerManager: ObservableObject {
    @Published var cacheItems: [PrunableCacheItem] = []
    @Published var isScanning = false
    @Published var isPruning = false
    
    private let fileManager = FileManager.default
    
    func scanCaches() {
        self.isScanning = true
        self.cacheItems = []
        
        AppLogger.shared.log("Scanning developer caches...")
        
        Task.detached(priority: .userInitiated) {
            let home = FileManager.default.homeDirectoryForCurrentUser.path
            
            let targets: [(name: String, path: String, description: String)] = [
                // Xcode / Apple
                ("Xcode Derived Data", "\(home)/Library/Developer/Xcode/DerivedData", "Temporary build files, indexes, and logs generated by Xcode during project compilation."),
                ("Xcode iOS DeviceSupport", "\(home)/Library/Developer/Xcode/iOS DeviceSupport", "iOS developer symbols used for symbolication and debugging on physical iOS devices."),
                ("Xcode watchOS DeviceSupport", "\(home)/Library/Developer/Xcode/watchOS DeviceSupport", "watchOS developer symbols used for debugging on Apple Watch devices."),
                ("Xcode tvOS DeviceSupport", "\(home)/Library/Developer/Xcode/tvOS DeviceSupport", "tvOS developer symbols for Apple TV debugging."),
                ("Xcode Simulator Caches", "\(home)/Library/Developer/CoreSimulator/Caches", "Simulator runtime caches and downloaded runtime images for iOS and other platforms."),
                ("Xcode Archives", "\(home)/Library/Developer/Xcode/Archives", "Xcode app archive bundles. Safe to remove if already uploaded to App Store Connect."),
                ("Xcode Previews", "\(home)/Library/Developer/Xcode/UserData/Previews", "SwiftUI Preview rendering caches and compiled preview binaries."),
                ("Swift Package Manager Cache", "\(home)/Library/Caches/org.swift.swiftpm", "Resolved Swift package source and build caches from Swift Package Manager."),
                ("Swift Package Manager (alternate)", "\(home)/.cache/org.swift.swiftpm", "Alternate SPM cache path used on some macOS and Linux configurations."),
                // Node.js / JavaScript
                ("npm Cache", "\(home)/.npm", "Global caches stored by Node Package Manager (npm) for faster future package downloads."),
                ("pnpm Store", "\(home)/Library/pnpm/store", "Immutable content-addressable package store used by pnpm package manager."),
                ("Yarn Classic Cache", "\(home)/Library/Caches/Yarn", "Cached archives of packages installed by the Yarn classic (v1) package manager."),
                ("Yarn Berry Cache", "\(home)/.yarn/berry/cache", "Cached package zip files created by Yarn version 2+ (Berry/PnP)."),
                ("Bun Cache", "\(home)/.bun/install/cache", "Package installations cached locally by the Bun JavaScript runtime and installer."),
                ("Deno Cache", "\(home)/Library/Caches/deno", "Remote module and TypeScript compile caches used by the Deno runtime."),
                ("Node.js Compiled Addons Cache", "\(home)/.node_gyp", "Compiled native Node.js addon build caches from node-gyp."),
                ("Next.js Build Cache", "\(home)/.next", "Next.js incremental build cache files stored in project-level .next directories."),
                ("Vite Build Cache", "\(home)/.vite", "Vite bundler pre-bundled dependency caches."),
                // Python
                ("pip Cache", "\(home)/Library/Caches/pip", "pip package download cache for faster Python dependency installation."),
                ("pyenv Shims", "\(home)/.pyenv/shims", "Shell shim binaries generated by pyenv for Python version intercept."),
                ("Conda Package Cache", "\(home)/opt/anaconda3/pkgs", "Cached Conda package tarballs and downloaded environments."),
                ("Poetry Cache", "\(home)/Library/Caches/pypoetry", "Cached wheel builds and dependency files stored by the Poetry Python package manager."),
                ("Jupyter Notebook Checkpoints", "\(home)/.ipynb_checkpoints", "Auto-saved notebook checkpoint files created by Jupyter."),
                ("mypy Cache", "\(home)/.mypy_cache", "Incremental type-checking cache files generated by mypy."),
                ("pytest Cache", "\(home)/.pytest_cache", "pytest incremental test result caches."),
                ("Ruff Cache", "\(home)/.ruff_cache", "Linting results cache used by the Ruff Python linter."),
                // Ruby
                ("RubyGems Cache", "\(home)/.gem/cache", "Downloaded Ruby gem package archives cached by RubyGems."),
                ("Bundler Cache", "\(home)/.bundle/cache", "Bundled gem caches stored locally by the Bundler dependency manager."),
                // Rust / Go / Java
                ("Cargo Target Directory (user)", "\(home)/.cargo/target", "Compiled Rust build artifacts in the user-level Cargo target directory."),
                ("Cargo Registry", "\(home)/.cargo/registry", "Caches of downloaded crate packages index and sources used by Cargo (Rust)."),
                ("Cargo Git Caches", "\(home)/.cargo/git", "Cloned git repositories for Cargo packages defined as Git dependencies."),
                ("Go Module Cache", "\(home)/go/pkg/mod", "Cached Go module source tarballs for all downloaded dependencies."),
                ("Go Build Cache", "\(home)/Library/Caches/go-build", "Compiled Go binary caches that speed up incremental builds."),
                ("Gradle User Home Cache", "\(home)/.gradle/caches", "Gradle build system cached artifact downloads and build outputs."),
                ("Maven Local Repository", "\(home)/.m2/repository", "Maven artifact cache containing downloaded JARs, POMs, and plugins."),
                ("Java JVM Compiled Output", "\(home)/IdeaProjects", "IntelliJ IDEA project build outputs and compiled class files."),
                // Homebrew & macOS
                ("Homebrew Download Cache", "\(home)/Library/Caches/Homebrew", "Downloaded formulas, casks, tarballs, and git repos cached by the Homebrew package manager."),
                ("Homebrew Locks", "\(home)/Library/Locks/Homebrew", "Stale lockfiles left behind by Homebrew during interrupted installations."),
                // Docker
                ("Docker Desktop Logs", "\(home)/Library/Containers/com.docker.docker/Data/log", "Diagnostic logging and runtime temporary caches from Docker Desktop containers."),
                // Misc Dev Tools
                ("CocoaPods Cache", "\(home)/Library/Caches/CocoaPods", "Downloaded CocoaPods pod tarballs and checksums for iOS/macOS projects."),
                ("Fastlane Cache", "\(home)/.fastlane", "Fastlane build automation tool metadata and deployment caches."),
                ("Swiftlint Cache", "\(home)/Library/Caches/SwiftLint", "SwiftLint rule compilation caches."),
                ("Ruby on Rails Log Files", "\(home)/.config/rails/log", "Rails framework log caches stored in home config directory."),
                ("Vim Plugin Cache", "\(home)/.vim/plugged/.vim-cache", "Vim editor plugin and syntax cache files."),
                ("VS Code Extension Cache", "\(home)/Library/Application Support/Code/CachedExtensions", "Visual Studio Code marketplace extension download caches."),
                ("VS Code Electron Cache", "\(home)/Library/Application Support/Code/Cache", "Electron shell cache files used by VS Code's browser rendering engine."),
                ("IntelliJ IDEA System Cache", "\(home)/Library/Caches/JetBrains", "JetBrains IDE system caches including indices, stub files, and VFS data."),
                ("Android SDK Build Tools Cache", "\(home)/Library/Android/sdk/build-tools", "Android SDK build tool binaries downloaded by Android Studio."),
                ("Terraform Plugin Cache", "\(home)/.terraform.d/plugins", "Locally cached Terraform provider plugin binaries."),
            ]
            
            var scanned: [PrunableCacheItem] = []
            
            for target in targets {
                if FileManager.default.fileExists(atPath: target.path) {
                    let size = self.getPathSize(URL(fileURLWithPath: target.path))
                    // Only display if the cache has files (size > 0)
                    if size > 0 {
                        scanned.append(PrunableCacheItem(
                            name: target.name,
                            path: target.path,
                            description: target.description,
                            size: size,
                            isSelected: true
                        ))
                    }
                }
            }
            
            // Check Docker CLI df size as well
            let dockerBinPaths = ["/usr/local/bin/docker", "/opt/homebrew/bin/docker"]
            for dockerBin in dockerBinPaths where FileManager.default.fileExists(atPath: dockerBin) {
                if let dfSize = self.getDockerDfSize(dockerBin: dockerBin), dfSize > 0 {
                    scanned.append(PrunableCacheItem(
                        name: "Docker Dangling Images & Volumes",
                        path: dockerBin, // Use bin path as identifier
                        description: "Dangling or unused Docker images, stopped containers, and unreferenced build cache items.",
                        size: dfSize,
                        isSelected: false // Safe default
                    ))
                }
                break
            }
            
            await MainActor.run {
                self.cacheItems = scanned.sorted(by: { $0.size > $1.size })
                self.isScanning = false
                AppLogger.shared.log("Cache scan finished. Found \(self.cacheItems.count) developer cache targets.")
            }
        }
    }
    
    func pruneSelectedCaches(completion: @escaping (Bool) -> Void) {
        self.isPruning = true
        let itemsToPrune = cacheItems.filter { $0.isSelected }
        
        AppLogger.shared.log("Pruning \(itemsToPrune.count) developer cache directories...")
        
        Task.detached(priority: .userInitiated) {
            var success = true
            
            for item in itemsToPrune {
                // If it's a Docker system prune (identified by binary path)
                if item.path.hasSuffix("/docker") {
                    AppLogger.shared.log("Running Docker prune commands...")
                    let pruned = self.runDockerPrune(dockerBin: item.path)
                    if !pruned {
                        success = false
                    }
                    continue
                }
                
                // Otherwise standard file trashing
                do {
                    let url = URL(fileURLWithPath: item.path)
                    if FileManager.default.fileExists(atPath: item.path) {
                        AppLogger.shared.log("Trashing: \(item.path)")
                        try FileManager.default.trashItem(at: url, resultingItemURL: nil)
                    }
                } catch {
                    AppLogger.shared.log("Failed to clean \(item.name): \(error.localizedDescription)")
                    success = false
                }
            }
            
            await MainActor.run {
                self.cacheItems.removeAll { $0.isSelected }
                self.isPruning = false
                AppLogger.shared.log("Pruning completed.")
                completion(success)
            }
        }
    }
    
    private func getPathSize(_ url: URL) -> Int64 {
        var isDirectory: ObjCBool = false
        guard FileManager.default.fileExists(atPath: url.path, isDirectory: &isDirectory) else {
            return 0
        }
        
        if isDirectory.boolValue {
            var size: Int64 = 0
            guard let enumerator = FileManager.default.enumerator(at: url, includingPropertiesForKeys: [.fileSizeKey], options: [.skipsHiddenFiles]) else {
                return 0
            }
            for case let fileURL as URL in enumerator {
                if let fileSize = try? fileURL.resourceValues(forKeys: [.fileSizeKey]).fileSize {
                    size += Int64(fileSize)
                }
            }
            return size
        } else {
            if let attrs = try? FileManager.default.attributesOfItem(atPath: url.path),
               let fileSize = attrs[.size] as? Int64 {
                return fileSize
            }
            return 0
        }
    }
    
    private func getDockerDfSize(dockerBin: String) -> Int64? {
        let process = Process()
        process.executableURL = URL(fileURLWithPath: dockerBin)
        process.arguments = ["system", "df", "--format", "{{.Reclaimable}}"]
        
        let pipe = Pipe()
        process.standardOutput = pipe
        process.standardError = Pipe()
        
        do {
            try process.run()
            process.waitUntilExit()
            
            guard process.terminationStatus == 0 else { return nil }
            let data = pipe.fileHandleForReading.readDataToEndOfFile()
            guard let output = String(data: data, encoding: .utf8) else { return nil }
            
            var total: Int64 = 0
            for line in output.split(separator: "\n") {
                let raw = line.split(separator: " ").first.map(String.init) ?? ""
                if let bytes = parseHumanBytes(raw) {
                    total += bytes
                }
            }
            return total
        } catch {
            return nil
        }
    }
    
    private func runDockerPrune(dockerBin: String) -> Bool {
        let process = Process()
        process.executableURL = URL(fileURLWithPath: dockerBin)
        // Force prune build cache, containers, volumes and images
        process.arguments = ["system", "prune", "-af"]
        
        let pipe = Pipe()
        process.standardOutput = pipe
        process.standardError = pipe
        
        do {
            try process.run()
            process.waitUntilExit()
            
            let success = process.terminationStatus == 0
            if success {
                AppLogger.shared.log("Docker system prune completed successfully.")
            } else {
                let errData = pipe.fileHandleForReading.readDataToEndOfFile()
                let errStr = String(data: errData, encoding: .utf8) ?? "Unknown docker error"
                AppLogger.shared.log("Docker prune failed: \(errStr)")
            }
            return success
        } catch {
            AppLogger.shared.log("Error running Docker prune: \(error.localizedDescription)")
            return false
        }
    }
    
    private func parseHumanBytes(_ s: String) -> Int64? {
        let trimmed = s.trimmingCharacters(in: .whitespaces)
        guard !trimmed.isEmpty else { return nil }
        let units: [(String, Double)] = [
            ("TB", 1_000_000_000_000),
            ("GB", 1_000_000_000),
            ("MB", 1_000_000),
            ("kB", 1_000),
            ("KB", 1_000),
            ("B", 1)
        ]
        for (suffix, multiplier) in units {
            if trimmed.hasSuffix(suffix) {
                let numberPart = String(trimmed.dropLast(suffix.count))
                if let value = Double(numberPart) {
                    return Int64(value * multiplier)
                }
            }
        }
        return nil
    }
}
