name: PR Size Labeler

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  label:
    name: Check Diff Lines and Label PR Size
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Calculate Diff Size and Label PR
        uses: pascalgn/size-label-action@v0.5.5
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          SIZES: >
            {
              "0": "size/XS",
              "50": "size/S",
              "200": "size/M",
              "500": "size/L",
              "1000": "size/XL"
            }
