name: Inactive Issues & PRs Closer

on:
  schedule:
    - cron: '0 6 * * *' # Daily at 06:00

jobs:
  stale:
    name: Flag and Close Stale Items
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Close Stale Issues and PRs
        uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue is stale because it has been inactive for 30 days. It will be closed in 7 days if no further activity occurs.'
          stale-pr-message: 'This Pull Request is stale because it has been inactive for 30 days. It will be closed in 7 days if no further actions are taken.'
          days-before-stale: 30
          days-before-close: 7
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
